Author.create(:name => "Christina Baker Kline")
Author.create(:name => "Nora Roberts")
Author.create(:name => "Paulo Coelho")
Author.create(:name => "David Baldacci")
Author.create(:name => "George R R Martin")
Author.create(:name => "Chimamanda Ngozi Adichie")
Author.create(:name => "Jojo Moyes")
Author.create(:name => "Elizabeth Strout")
Author.create(:name => "Meg Wolitzer")
Author.create(:name => "Kristin Hannah")
Author.create(:name => "Jess Walter")
Author.create(:name => "M L Stedman")
Author.create(:name => "Ruth Ozeki")
Author.create(:name => "Edward Rutherfurd")
Author.create(:name => "Elin Hilderbrand")
Author.create(:name => "Gillian Flynn")
Author.create(:name => "Ron Carr")
Author.create(:name => "Philippa Gregory")

Review.create(:book_id => 1, :rating => 5, :comment => "Riveting!")
Review.create(:book_id => 1, :rating => 2, :comment => "About as dull as you can get.")
Review.create(:book_id => 1, :rating => 3, :comment => "Not bad.")
Review.create(:book_id => 2, :rating => 4, :comment => "Great book, and not too many pages.")
Review.create(:book_id => 2, :rating => 4, :comment => "Excellent font and margins. Story wasn't bad, either.")
Review.create(:book_id => 2, :rating => 4, :comment => "Worth reading when there isn't a hockey game on.")
Review.create(:book_id => 2, :rating => 1, :comment => "Didn't understand it at all.")
Review.create(:book_id => 3, :rating => 2, :comment => "I thought this was about how to make gold?")
Review.create(:book_id => 3, :rating => 4, :comment => "Suspensful plot, good characters.")
Review.create(:book_id => 3, :rating => 5, :comment => "Perfect. A work of art.")
Review.create(:book_id => 3, :rating => 3, :comment => "kind of confusing.")


Book.create(:title => "Orphan Train", :author_id => 1, :price => 26)
Book.create(:title => "Shadow Spell", :author_id => 2, :price => 15)
Book.create(:title => "The Alchemist", :author_id => 3, :price => 12)
Book.create(:title => "King And Maxwell", :author_id => 4, :price => 35)
Book.create(:title => "Whiskey Beach", :author_id => 2, :price => 22)
Book.create(:title => "A Game Of Thrones", :author_id => 5, :price => 24)
Book.create(:title => "Americanah", :author_id => 6, :price => 20)
Book.create(:title => "Me Before You", :author_id => 7, :price => 18)
Book.create(:title => "The Burgess Boys", :author_id => 8, :price => 15)
Book.create(:title => "The Interestings", :author_id => 9, :price => 27)
Book.create(:title => "Fly Away", :author_id => 10, :price => 23)
Book.create(:title => "Beautiful Ruins", :author_id => 11, :price => 14)
Book.create(:title => "The Light Between Oceans", :author_id => 12, :price => 25)
Book.create(:title => "A Tale For The Time Being", :author_id => 13, :price => 34)
Book.create(:title => "Paris", :author_id => 14, :price => 38)
Book.create(:title => "Beautiful Day", :author_id => 15, :price => 16)
Book.create(:title => "Dark Places", :author_id => 16, :price => 15)
Book.create(:title => "Four Friends", :author_id => 17, :price => 20)
Book.create(:title => "The White Princess", :author_id => 18, :price => 24)


# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
